### ISSUE TITLE
3.1.0: TypeErrors

### ISSUE THREAD

**Issue by schildbach** [janoside/btc-rpc-explorer#320]
**Describe the bug**

After upgrading from 2.2.0 to 3.1.0, I get several cryptic TypeErrors and the website cannot be reached:

```
2021-04-17T16:43:43.366Z btcexp:error Error 3289023yege: TypeError: process.hrtime.bigint is not a function, json: {}
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  | 2021-04-17T16:43:43.367Z btcexp:error Error 2309832hcxwgeeew: TypeError: /workspace/views/layout.pug:15
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |     13|
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |     14|
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |   > 15|                 if (userSettings.uiTheme == "light")
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |     16|                         link(rel="stylesheet", href="./style/light.css", integrity="sha384-g29RQdd+TbXjjBSuwxb0PuDyrEcBhwSZ7JRL21EgNUQsP7XAXGvjiP1EhgHnL/Hj")
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |     17|
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |     18|                 else
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  | Cannot read property 'uiTheme' of undefined, json: {"path":"/workspace/views/layout.pug"}
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  | TypeError: /workspace/views/layout.pug:15
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |     13|
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |     14|
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |   > 15|                 if (userSettings.uiTheme == "light")
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |     16|                         link(rel="stylesheet", href="./style/light.css", integrity="sha384-g29RQdd+TbXjjBSuwxb0PuDyrEcBhwSZ7JRL21EgNUQsP7XAXGvjiP1EhgHnL/Hj")
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |     17|
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |     18|                 else
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  |
Apr 17 16:43:43 nas docker-compose[1353578]: btc-rpc-explorer_1  | Cannot read property 'uiTheme' of undefined
```

**Environment (please complete the following information):**

 - The Docker image, running inside Docker-Compose
 - Bitcoin Core 0.21.0
 - electrs 0.8.9
 - traefik 2.4.7
 - Browser: Firefox 87.0

**Configuration file content**

```
      - BTCEXP_DEBUG=btcexp:*
      - BTCEXP_COIN=BTC
      - BTCEXP_HOST=0.0.0.0
      - BTCEXP_BITCOIND_URI=bitcoin://bitcoind:${BITCOIND_RPC_PORT}
      - BTCEXP_BITCOIND_COOKIE=/run/secrets/bitcoind_rpc_cookie
      - BTCEXP_ADDRESS_API=electrumx
      - BTCEXP_ELECTRUM_SERVERS=tcp://electrs:${ELECTRS_TCP_PORT}
      - BTCEXP_PRIVACY_MODE=true
```

**Comment by janoside** [comment]
What version of node?

**Comment by schildbach** [comment]
> What version of node?

It's the Docker image. How can I find out?

**Comment by janoside** [comment]
@schildbach Thanks for that info. The docker image was on node 8 which was causing the problems you encountered. There's a new update, v3.1.1, with an updated Dockerfile that uses node 14 and should fix this problem for you.

I'm closing this issue, but please reply back if you encounter this problem after updating.

**Comment by schildbach** [comment]
This fixes the problem. Thanks!
